---
driver:
  name: vagrant

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: true
  require_ansible_omnibus: true
  ansible_verbosity: 3
  ansible_verbose: true
# Fix for: https://github.com/ansible/ansible/issues/23016
  ansible_version: 2.2.0
  extra_vars:
    sphinx_test: true

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-9.12
  - name: debian-10.3

suites:
  - name: default

# Fix for: https://github.com/neillturner/kitchen-ansible/issues/66
verifier:
  ruby_bindir: '/usr/bin'
