---

- name: Install sphinx Debian package
  apt: name="{{ ubuntu_pkg }}" state=present update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install sphinx RedHat dependencies
  yum: name="{{ rhel_dep_pkg }}" state=present
  when: ansible_os_family == "RedHat"

- name: Install sphinx RedHat package
  yum:
    name: "{{ rhel_pkg }}"
    state: present
  when: ansible_os_family == "RedHat"
