---

- name: Install sphinx Debian package
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ ubuntu_pkg }}"
  when: ansible_os_family == "Debian"

- name: Install sphinx RedHat dependencies
  yum: name={{ item }} state=present
  with_items:
    - postgresql-libs
    - unixODBC
  when: ansible_os_family == "RedHat"

- name: Install sphinx RedHat package
  yum:
    name: "{{ rhel_pkg }}"
    state: present
  when: ansible_os_family == "RedHat"
