---

- name: Create xml file for testing purpose
  copy:
    src: test.xml
    dest: /tmp/test.xml
    owner: root
    group: root
    mode: 0644
  notify:
    - generate all indexes
  tags:
    - test
