---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: bento/ubuntu-20.04
    memory: 512
    cpus: 1
lint: |
  set -e
  yamllint *.yml
  ansible-lint
#  flake8
provisioner:
  name: ansible
verifier:
  name: ansible
