---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Example assertion
    command: /usr/local/bin/bats ./test/integration/default/bats/*.bats
  - name: Example assertion
    assert:
      that: true
